apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentledger.fullname" . }}
  labels:
    {{- include "agentledger.labels" . | nindent 4 }}
data:
  agentledger.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
